# Generated by Django 5.2.6 on 2025-09-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='video',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='usuario@correo.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='video',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
